### ISSUE TITLE
Is it ok on Android？

### ISSUE THREAD

**Issue by whitelok** [greenlaw110/rythm-doc#37]
On Android, I got these exception: "Ljava/lang/RuntimeException; thrown while initializing Lorg/rythmengine/internal/dialect/SimpleRythm;" and "Ljava/lang/ExceptionInInitializerError; thrown while initializing Lorg/rythmengine/internal/dialect/DialectManager;"

**Comment by greenlaw110** [comment]
Can you please open the issue on https://github.com/greenlaw110/rythm/issues? this project is purely about document.

Please put in full stack trace of the exception when you open the issue on rythm project. thank
