### ISSUE TITLE
为什么跟着HelloWorld程序做，总是输出helloworld.html，不输出其内容？

### ISSUE THREAD

**Issue by qixizhu** [greenlaw110/rythm-doc#38]
都检查好多遍了，前几个步骤都好好的，我也确定在build.xml配置了正确的代码，直接复制过来的。

**Comment by qixizhu** [comment]
终于找到解决方法了，不知道是官网的事例有问题，还是我没配置好。
System.out.println(Rythm.render( new File("E:\...\HelloWorld\resources\helloworld.html"), np.from(np.pair("who", "World"), np.pair("action", "Greeting"))));

**Comment by greenlaw110** [comment]
恭喜你自己解决问题了。等有时间了我会重写教程，改用Maven就不会出现找不到资源的问题
