### ISSUE TITLE
How to call user defined method with 2 parameter in template

### ISSUE THREAD

**Issue by Himanshu-agnisys** [greenlaw110/rythm-doc#44]
I successfully call the method that have 1 parameter  but How to call user defined java method with 2 parameter in template like 
i have a method -:

```java
static String test(Object obj,String str){
//to do
}
```

how i call this method in rythm template .

please tell me asap..
Thanks

**Comment by greenlaw110** [comment]
@Himanshu-agnisys 

Suppose you defined that method in a class `com.mypkg.MyClass`, and your template is not put in a folde rnamed `com/mypkg/MyClass`, you won't be able to invoke that method unless you change that method to `public` scoped.

And to invoke a static public method from a public class you can do something like:

```
@com.mypkg.MyClass.test(new Object(), "some str");
```

Or if you need to invoke multiple methods in that class, you can import it:

```
@import com.mypkg.MyClass;

@MyClass.test(new Object(), "some str")
```

**Comment by Himanshu-agnisys** [comment]
Hi Green Luo,

Thank you for your Support.

Thanks & Regards
Himanshu Yadav 
Java Developer
